version: '3.8'

services:
  mixsync:
    build: .
    container_name: mixsync
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./downloads:/app/downloads
      - ./.spotify_cache:/app/.spotify_cache
      - ./.env:/app/.env:ro
    environment:
      # These can be overridden by .env file
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mixsync-network

networks:
  mixsync-network:
    driver: bridge
