version: '3.8'

services:
  mixsync:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./downloads:/app/downloads
      - ./audio_fetcher.db:/app/audio_fetcher.db
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
