version: '3.8'

services:
  mixsync:
    build:
      context: .
      dockerfile: Dockerfile.unraid
    container_name: mixsync
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      # Main app data directory
      - /mnt/user/appdata/mixsync/downloads:/app/downloads
      - /mnt/user/appdata/mixsync/config:/app/config
      - /mnt/user/appdata/mixsync/.spotify_cache:/app/.spotify_cache
      # Environment file (optional - can use env vars instead)
      - /mnt/user/appdata/mixsync/.env:/app/.env:ro
    environment:
      # Unraid user/group IDs
      - PUID=99
      - PGID=100
      # Spotify configuration (can also be set via .env file)
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI:-http://localhost:8888/callback}
      - SPOTIFY_PLAYLIST_ID=${SPOTIFY_PLAYLIST_ID}
      - POLL_INTERVAL_MINUTES=${POLL_INTERVAL_MINUTES:-10}
      - DOWNLOAD_PATH=/app/downloads
      # Python configuration
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mixsync-network

networks:
  mixsync-network:
    driver: bridge
