version: '3.9'

services:
  mixsync:
    build: .
    container_name: mixsync
    ports:
      - '8000:8000'
    volumes:
      - ./downloads:/app/downloads
      - ./env_example.txt:/app/.env # Optional env config
    restart: unless-stopped
